= CSS e JS
Marco Andreini <marco.andreini@besmartbeopen.it>
2016-02-23
:source-highlighter: highlightjs
:backend: revealjs
:revealjs_theme: night
:revealjs_slideNumber: true
:sourcedir: ../main/java

== L'informazione e la sua presentazione

La pagina web è utile per trasferire le informazioni. Quest'ultima ha due aspetti fondamentali:

i contenuti:: forniti con linguaggi di marcatura come HTML
la presentazione:: determinati dall'interpretazione browser

== Presentazione e browser

* Ogni browser ha un suo modo predefinito di presentare il contenuto
** a volte la presentazione è senbilmente diversa in funzione del browser
* Ci sono comportamenti grafici predefiniti per gli elementi HTML
* si possono comunque personalizzare i vari aspetti della presentazione
con l'uso degli *stili*

== Cascading Style Sheets (CSS)

* definiscono il modo con cui il browser presenta il contenuto
** la presentazione può riguardare più media (video, stampa, presentazione, audio, ...)
** non uniforma la presentazione, fornisce delle indicazioni

stylesheet:: sono documenti che comprendono un insieme di *regole di presentazione*
regole:: sono istruzioni che permettono di indicare l'aspetto stilistico di uno
o più elementi

== CSS: regole

.esempio
[source,css]
----
h1 { color: green }
----
Le regole utilizzano un linguaggio semplice ed intuitivo attraverso il quale è
abbastanza facile capirne la semantica, il linguaggio naturale di riferimento è
naturalmente l'inglese.

La regola dell'esempio sopra indica che il colore (`color`) del testo
degli elementi di tipo h1 viene impostato a verde (`green`).

== Regola

[cols=">,<"]
|===
|`h1`
|`{ color: green }`

|selettore
|dichiarazione
|===

selettore:: la parte prima delle parentesi graffe - specifica gli elementi
assoggettati a questa regola ed è il collegamento tra il documento HTML e lo
stile
dichiarazione:: la parte dentro le graffe - è la parte della regola che imposta il
comportamento stilistico degli oggetti coinvolti

== Dichiarazione

[source,css]
----
   h1        { color     : green  }
// selettore { proprietà : valore }
----

proprietà:: la parte prima dei due punti che descrive una caratteristica che un
oggetto può avere
valore:: la parte dopo i due punti che indica quale comportamento deve avere la
proprietà selezionata

== Raggrupamenti di regole

Raggruppare le regole perchè?

[%step]
* per semplificare la struttura e la scrittura dei CSS
* per razionalizzare gli stili
* per ridurre le dimensioni del foglio di stile

== Raggruppare le regole per dichiarazione

Riportando come selettore l'elenco dei singoli selettori separati da ","
[source,css]
----
h1, h2, h3 { font-weight: bold }
----
corrispondente a:
[source,css]
----
h1 { font-weight: bold }
h2 { font-weight: bold }
h3 { font-weight: bold }
----

== Raggruppare le regole per selettore:

usando lo stesso selettore, ma elencando le dichiarazioni separate da ";"
[source,css]
----
h1 { color: blue; font-weight: bold; text-align: center }
----
corrispondente a:
[source,css]
----
h1 { color: blue }
h1 { font-weight: bold }
h1 { text-align: center}
----

== Raggruppamento misto

Si possono anche mescolare le due tipologie di raggruppamento.
[source,css]
.esempio.css
----
h1, h2, h3 { color: blue; font-weight: bold }
----

== Associare i CSS alla pagina web

Si può indicare un foglio di stile ad una pagina HTML

[%step]
. utilizzando l'attributo `style` su uno o più elementi HTML
. utilizzando l'elemento `style` al documento HTML
. collegando un foglio di stile esterno per mezzo dell'elemento `link`

== Javascript

[%step]
* Il *javascript* è un linguaggio di programmazione interpretato
* inizialmente progettato per permettere l'esecuzione di script all'interno del
browser (quindi _lato client_)
* nato per dare la possibilità di interagire con l'utente in modo più diretto
* si utilizza il pattern event/observer per personalizzare le azioni dell'utente

== Esempio di javascript

Si inserisce nella pagina web con l'elemento `script`

[source,html]
----
<html>
 ...
  <script type="text/javascript">
    document.write('<p>Ciao mondo!</p>');
  </script>
 ...
</html>
----
