= Advanced JPA
Cristian Lucchesi <cristian.lucchesi@gmail.com>
2016-02-28
:source-highlighter: highlightjs
:backend: revealjs
:revealjs_theme: night
:revealjs_slideNumber: true
:sourcedir: ../main/java

== Relazioni e loro caratteristiche

* gli oggetti possono contenere uno o più riferimenti ad altri oggetti
** questi riferimenti prendono il nome di *relazioni*
* le relazioni hanno diverse caratteristiche
** *direzionalità*, una relazione potrà essere:
*** unidirezionale se un oggetto fa riferimento ad un altro ma non avviene il contrario
*** bidirezionale se il riferimento tra gli oggetti è reciproco

== Relazioni bidirezionali
[source,java]
----
@Entity
public class Person {
  private Account account;
}
@Entity
public class Account {
  // Possessore
  private Person owner;
}
----

La Person ha una relazione con Account e viceversa.

== Relazioni unidirezionali

[source,java]
----
@Entity
public class Person {
  //... Altre proprietà
  private Province bornIn;
}
@Entity
public class Province {
  private String name;
}
----

Person ha una relazione con Province ma non viceversa.

== Relazioni e opzionalità

** altra caratteristica delle relazioni è l'opzionalità:
*** non è detto che la relazione debba esistere necessariamente.
*** se non è obbligatoria, la relazione si dice opzionale.

== Relazioni e molteplicità^(3)^

* la relazione può sussistere verso uno o più oggetti, in entrambe le direzioni
* tre tipi di relazioni in funzione della molteplicità
** uno a uno, uno a molti, molti a molti

JPA permette di gestire le relazioni e di risparmiarci di scrivere molto codice

== Relazione uno a uno unidirezionale

[source,java]
----
@Entity @Table(name="persons")
public class Person {
  @OneToOne
  private Account account;
}
@Entity @Table(name="accounts")
public class Account {
  // Non c'è il campo Person
}
----

* si utilizza l’annotazione *@OneToOne*
* l'annotazione è solo nell’entità che possiede il riferimento (_owning side_)
* la tabella _persons_ avrà una colonna con la chiave esterna che si riferisce alla tabella _accounts_.

== Relazione uno a uno bidirezionale

[source,java]
----
@Entity @Table(name="persons")
public class Person {
  @OneToOne
  private Account account;
}
@Entity @Table(name="accounts")
public class Account {
  @OneToOne(mappedBy="account")
  private Person person;
}
----

* l'annotazione @OneToOne è su entrambe le entità (_owning side_ e _inverse side_)
* l'attributo *mappedBy* specifica il *nome* della proprietà java utilizzata nella @OneToOne che è _owning side_

== L'importanza dell'owning side

* il Persistence Runtime JPA (es. Hibernate) effettua aggiornamenti della relazione sul db solo quando si cambia l'owning side
[source,java]
----
@Entity @Table(name="persons")
public class Person {
  @OneToOne
  private Account account;
}
@Entity @Table(name="accounts")
public class Account {
  @OneToOne(mappedBy="account")
  private Person person;
}
...
Person p = entityManager.getReference(Person.class, 1L);
account.setPerson(p); // Non viene modificato il db

Account a = entityManager.getReference(Account.class, 1L);
person.setAccount(a); // viene aggiornato il db
----

== Caricamento delle relazioni

[source,java]
.Esempio di find
----
Person p = entityManager.find(Person.class, 1L);
----

[source,sql]
.query sql
----
select
  personwith0_.id as id1_3_1_, personwith0_.account_id as account_4_3_1_,
  personwith0_.name as name2_3_1_, personwith0_.surname as surname3_3_1_,
  account1_.id as id1_2_0_, account1_.username as username2_2_0_ 
from
  persons personwith0_ 
left outer join
  accounts account1_   on personwith0_.account_id=account1_.id
where
  personwith0_.account_id=1
----

L'EntityManager si occupa di caricare gli oggetti collegati con le opportune join.

== Annotazione @JoinColumn

* @JoinColumn permette di personalizzare la relazione:
** *name*: (String default il nome della variabile)
*** cambia il nome della colonna sul db
** *insertable*: (boolean default true) 
*** se false la colonna viene omessa nella insert
** *updatable*: (boolean default true) 
*** se false la colonna viene omessa nella update

== Annotazione @JoinColumn^(2)^

* @JoinColumn permette di personalizzare la relazione:
** *nullable* (boolean default true)
*** utilizzata per determinare il tipo di JOIN eseguita da jpa (INNER vs LEFT)
** columnDefinition (String default "")
*** frammento di SQL da utilizzare per la DDL della colonna

== Annotazione @JoinColumn^(3)^

[source,java]
----
@Entity @Table(name="persons")
public class Person {
  @OneToOne
  @JoinColumn(name="account_id", updatable = false)
  private Account account;
}
----

* viene indicato il nome della colonna da utilizzare per le join e che il campo non è aggiornabile

== Relazioni uno a molti

* un'entità può essere associata a più di un oggetto dello stesso tipo
* la relazione viene detta di tipo uno a molti.
* analogamente alle relazioni uno ad uno può essere uni o bidirezionale

In questo caso le annotazioni utilizzate sono:

* *javax.persistence.OneToMany*
* *javax.persistence.ManyToOne*

== Relazioni uno a molti^(2)^

[source,java]
----
@Entity @Table(name = "persons")
public class Person {
  @OneToMany(mappedBy = "owner")
  private List<Car> cars = new ArrayList();
}
@Entity @Table(name = "cars")
public class Car {
  @ManyToOne
  private Person owner;
}
----

* una persona ha molte macchine @OneToMany
* molte macchine hanno lo stesso (uno) proprietario @ManyToOne

== Relazioni uno a molti^(3)^

[source,java]
----
@Entity @Table(name = "orders")
public class Order {
  @Size(min = 1)
  @OneToMany(mappedBy = "order")
  private List<LineItem> lineItems = new ArrayList<>();
}
@Entity @Table(name = "order_line_items")
public class LineItem {
  @NotNull
  @ManyToOne(optional = false)
  private Order order;
}
----

* un ordine ha molte righe di dettaglio (almeno una)
* più righe di dettaglio appartengono allo stesso ordine
* una riga di dettaglio deve appartenere ad un ordine

== Utilizzo delle relazioni

[source,java]
.Esempio Java
----
Order order = entityManager.find(Order.class, 1L);
System.out.println("Ordine " + order);
for (LineItem lineItem : order.getLineItems()) {
  System.out.println(
    String.format("Riga %s. %s: %s euro",
    lineItem.getId(), lineItem.getDescription(),lineItem.getAmount()));
}
----

[source,sql]
.query sql
----
select order0_.id as id1_4_0_ from orders order0_ where order0_.id=1

select lineitems0_.order_id as order_id4_4_0_, lineitems0_.id as id1_1_0_,
  lineitems0_.id as id1_1_1_, lineitems0_.amount as amount2_1_1_,
  lineitems0_.description as descript3_1_1_,
  lineitems0_.order_id as order_id4_1_1_
from LineItem lineitems0_ where lineitems0_.order_id=1
----

* non c'è bisogno di preoccuparsi delle join... ci pensa JPA

== Relazioni uno a molti e owning side

* il possessore della relazione _owning side_ è sempre con @ManyToMany
* l'_inverse side_ è sempre con @OneToMany che è quella con l'attributo mappedBy
* il JPA Engine tiene traccia dei cambiamenti solo sull'owning side
** (come avviene per le relazioni @OneToOne)

[source,java]
----
Order order = entityManager.find(Order.class, 1L);
order.getLineItems().add(lineItem); // Non viene modificato il db

LineItem li = entityManager.find(LineItem.class, 1L);
li.setOrder(order); // viene aggiornato il db
----

== Relazioni molti a molti

* molte entità possono essere associate a molte altre entità dello stesso tipo
* la relazione viene detta di tipo molti a molti
* analogamente alle relazioni _one-to-one e_ e _uno-to-many_ può essere uni o bidirezionale
* l'annotazione utilizzata è *javax.persistence.ManyToMany*
* nelle _many-to-many_ l'_owning_side_ può essere a scelta su uno qualunque dei lati della relazione

== Relazioni molti a molti^(2)^

[source,java]
----
@Entity @Table(name = "persons")
public class Person {
  @ManyToMany(mappedBy = "owners")
  private List<House> houses = new ArrayList();
}
@Entity @Table(name = "houses")
public class House {
  @ManyToMany
  private List<Person> owner = new ArrayList();
}
----

* una persona può avere molte case
* una casa può avere più proprietari

== @JoinTable

* specifica la tabella di mapping dell'associazione.
* è applicata al _owning side_ dell'associazione
* di solito è utilizzata nelle _many-to-many_ e _one-to-many_ unidirezionali
* se non è presente il nome della _join table_ è la concatenazione dei nomi delle tabelle in relazione tra di loro, separati da _ (underscore) e con l'_owning size_ prima

[source,java]
----
@ManyToMany
@JoinTable(name = "persons_houses")  
private List<Person> owner = new ArrayList();
----

== @JoinTable: joinColumns, inverseJoinColumns

[source,java]
----
@ManyToMany
@JoinTable(name = "persons_houses",
   joinColumns=  @JoinColumn(name="house_id"), <1>
   inverseJoinColumns= @JoinColumn(name="person_id") <2>
   )
private List<PersonWithAccount> owners = Lists.newArrayList();
----

<1> colonna del db relativa alla _owning_side_ dlela relazione
<2> colonna del db relativa alla _inverse_side_ della relazione


== Ordine di salvataggio degli oggetti dipendenti

[source,java]
----
//...
entityManager.getTransaction().begin();
Order order = new Order();
LineItem lineItem = new LineItem();
lineItem.setOrder(order);
entityManager.persist(lineItem); <1>
entityManager.persist(order);
entityManager.getTransaction().commit();
----

<1> In questo punto l'order non è ancora salvato (non ha un id associabile in _order_line_items_)

--
WARN: HHH000437: Attempting to save one or more entities that have a non-nullable association with an unsaved transient entity. The unsaved transient entity must be saved in an operation prior to saving these dependent entities.
--

== Cascade e Relazioni

.Table Operazioni in cascata per le Entity

* quando un'operazione è effettuata su un'entity si può scatenare la stessa operazione sulle entità collegate

[cols="1,4", options="header"]
|===
| Cascade | Descrizione

| PERSIST
| quando l'oggetto è _persisted_, anche l'entità collegata è _persisted_

| DETACH
| quando l'oggetto è _detached_, anche l'entità collegata è _detached_

| MERGE
| quando l'oggetto è _merged_, anche l'entità collegata è _merged_

|===

== Cascade e Relazioni

.Table Operazioni in cascata per le Entity^(cont)^

[cols="1,4", options="header"]
|===
| Cascade | Descrizione

| REFRESH
| quando viene effettuta la _refresh_ dell'oggetto anche l'entità collegata viene ricaricata

| REMOVE
| quando viene rimosso l'oggetto anche l'entità collegata viene rimosa

| ALL
| tutte le operazioni sono applicate agli oggetti correlati. Equivalente a cascade={DETACH, MERGE, PERSIST, REFRESH, REMOVE}

|===

== cascade = CascadeType.*

* Valido per tutte le relazioni @OneToOne, @OneToMany, @ManyToOne, ..

[source,java]
----
import javax.persistence.CascadeType;
//...
public class Order {
//...
  @OneToMany(mappedBy = "order", cascade = { CascadeType.PERSIST, CascadeType.REMOVE)
  private List<LineItem> lineItems = new ArrayList<>();
----


== Esempio di CascadeType.Persist

[source,java]
----
public class Order {
  //..
  @OneToMany(mappedBy = "order", cascade = CascadeType.PERSIST)
  private List<LineItem> lineItems = new ArrayList<>();
}

//...
// utilizzo del Cascade
Order order = new Order();
LineItem lineItem = new LineItem();
lineItem.setOrder(order);
order.getLineItems().add(lineItem);
entityManager.persist(order);
----

L'oggetto LineItem viene salvato per effetto del +
cascade = CascadeType.PERSIST


== Esempio di CascadeType.REMOVE

[source,java]
----
public class Order {
  //..
  @OneToMany(mappedBy = "order", cascade = { CascadeType.PERSIST, CascadeType.REMOVE )
  private List<LineItem> lineItems = new ArrayList<>();
}

//...
// utilizzo del Cascade
Order order = entityManager.find(Order.class, 1L);
entityManager.remove(order);
----

[source,sql]
----
Hibernate:
    select * from orders where id = 1
Hibernate:
    select * from order_line_items where order_id = 1
Hibernate: 
    delete from order_line_items where id = 1
Hibernate: 
    delete from orders where id = 1
----


== Orphan Removal

* nelle relazioni _one-to-one_ e _one-to-many_ quando un oggetto viene rimosso da una relazione è probabile che debba essere rimosso
* questi oggetti sono considerati *orphans* e possono essere rimossi automaticamente utilizzando l'attributo _orphanRemoval_
* per esempio se un Order ha molti LineItem ed un LineItem viene rimosso dall'associazione, la LineItem è considerata un _orphan_
* se orphanRemoval è true, la LineItem sarà cancellata quando è rimossa l'associazione dall'ordine

* l'attributo *orphanRemoval* in @OneToMany e @OneToOne accettata true/false ed il default è false


== Esempio di Orphan Removal^(2)^

[source,java]
----
public class Order {
  @OneToMany(mappedBy = "order", orphanRemoval = true)
  public List<LineItems> getLineItems() { ... }
}
// Esempio di utilizzo
Order order = entityManager.getReference(Order.class, 11L)
order.getLineItems().clear(); <1>
----

<1> La lista viene svuotata, gli oggetti LineItem diventano _orphan_ e vengono cancellati

== Quering Entities

JPA fornisce due metodi per interrogare le Entity

* Java Persistence query language (JPQL)
** linguaggio semplice basasto su stringhe e simile a SQL
* Criteria API
** un API Java utlizzata per creare query typesafe

== Java Persistence query language

* JPQL definisce le query per interrogare le Entity ed il loro stato di persistenza
* le query sono portabili ed indipendenti dal data store (db)
* il linguaggio utilizza le Entity e le loro relazioni come modello di astrazione del database
** le operazioni e le espressioni sono basate sul modello astratto
* lo _scope_ delle query comprende le Entity gestite dalla stessa Persistent Unit

[source,sql]
----
SELECT a FROM Article a ORDER BY a.date ASC
----

== Creazione delle Query con JPQL

EntityManager::createQuery permette di creare query dinamiche definite direttamente nella business logic dell'applicazione

[source,java]
----
@PersistenceContext
EntityManager entityManager;

public List<Person> list(int maxResults) {
  return entityManager
      .createQuery(
          "SELECT p FROM Person p", Person.class)
     .setMaxResults(maxResults)          
     .getResultList();
}
----

== @NamedQuery

* Si possono definire query statiche con nome
** Raccomandate perché le query usufruiscono del sistema di *cache*
[source,java]
----
@NamedQuery(name="ordered",  query="SELECT e FROM BlogEntry e ORDER BY e.date ASC")
public class BlogEntry {
...
----

[source,java]
----
public List<BlogEntry> allEntriesOrdered() {
    return entityManager.createNamedQuery("ordered", BlogEntry.class).getResultList();
}
----

== Named Parameter

* sono parametri della query prefissati con due punti (:).
* sono sostituiti nella query eseguita tramite il metodo
** `javax.persistence.Query.setParameter(String name, Object value)`

[source,java]
----
@PersistenceContext
EntityManager entityManager;

public List<Person> byName(String firstname) {
  return entityManager
      .createQuery(
          "SELECT p FROM Person p WHERE p.firstname = :firstname",
          Person.class)
     .setParameter("firstname", firstname)
     .getResultList();
}
----

== Positional Parameter

* parametri individuati con il punto interrogativo (?) seguiti da un numero
* sono sostituiti nella query eseguita tramite il metodo
** `javax.persistence.Query.Query.setParameter(integer position, Object value)`

[source,java]
----
@PersistenceContext
EntityManager entityManager;

public List<Person> byName(String firstname) {
  return entityManager
      .createQuery(
          "SELECT p FROM Person p WHERE p.firstname = ?1",
          Person.class)
     .setParameter(1, firstname)
     .getResultList();
}
----

== SELECT statement

* una select query ha sei elementi
** SELECT, FROM, WHERE, GROUP BY, HAVING e ORDER BY
* le clausole SELECT e FROM sono obbligatorie
* WHERE, GROUP BY, HAVING, and ORDER sono opzionali

[source,bnf]
----
QL_statement ::= select_clause from_clause 
  [where_clause][groupby_clause][having_clause][orderby_clause]
----

== SELECT e WHERE

* SELECT definisce il tipo di oggetto o valore restituto
* FROM definisce il contesto della query dichiarando uno o più variabili referenziabili nella parte SELECT e WHERE, può contenere
** il nome astratto di un'entità 
** una collezione riferita in un'entity
** un elemento single-valued di una relazione
* WHERE è un'espressione condizionale che restringe gli oggetti restituiti dalla query

== GROUP BY, HAVING, ORDER BY

* GROUP BY ragrruppa i risutalti della query in accordo ad un insieme di proprietà
* HAVING è utilizzata con la GROUP BY per restringere i risultati in accordo a delle espressioni condizionali
* definisce l'ordinamento dei risultati 

== Basic Example SELECT

[source,java]
----
SELECT p FROM Player p
----

dati restituiti:: tutti i giocatori
descrizione:: la clausola FROM dichiara un variabile identificativa chiamata *p*, omettendo la keyword opzionale *AS*
Player::
è l'abstract schema name dell'entity Player `@Entity class Player {...}`


== Eliminare i duplicati

[source,java]
----
SELECT DISTINCT p FROM Player p
  WHERE p.position = :position AND p.name = :name
----

dati restituti:: i giocatori con una determinata posizione e nome
descrizione::
* position e name sono campi persistenti dell'entità Player.
* nella WHERE si compare il valore dei campi nel db con quelli passati per parametro.
* *DISTINCT" elimina eventuali duplicati


== Navigare le relazioni

* in JPQL un'espressione può attraversare o navigare le entità correlate tra di loro
* questa funzionalità è la differenza principale tra JPQL e SQL
* la nagivazione tra le entità correlate è molto semplificata rispetto all'SQL perché sfrutta la descrizione delle entity e delle sue relazioni

== Simple Query con relazioni

[source]
----
SELECT DISTINCT p
  FROM Player p JOIN p.teams t
----

dati restituiti:: tutti i giocatori che appartengono almeno ad una squadra

descrizione::
* *p* rappresenta l'entità _Player_, *t* l'entità _Team_ correlata 
* *p.teams* naviga da un Player ai suoi Team correlati.
* il punto (.)  nell'espressione  *p.teams* è l'operatore di navigazione


== Simple Query con relazioni^(2)^

[source]
----
SELECT DISTINCT p
  FROM Player p JOIN p.teams t
----

è equivalente a

[source]
----
SELECT DISTINCT p
  FROM Player p
  WHERE p.team IS NOT EMPTY
----

ed a 

[source]
----
SELECT DISTINCT p
  FROM Player p, IN (p.teams) t
----

== Attraversare le relazioni

[source]
----
SELECT DISTINCT p
  FROM Player p JOIN p.teams
  WHERE t.city = :city
----

dati restituiti:: tutti i giocatori che appartengono ad una squadra di una determinata città

ATTENZIONE: nelle WHERE non si possono navigare le collezioni, non si può scrivere WHERE t.teams.city = :city (illegal expression)

== Navigazione basata su campi correlati

[source]
----
SELECT DISTINCT p
  FROM Player p JOIN p.teams t
  WHERE t.league.sport = :sport
----

* dato che *league* non è una collezione ma relazione *league* può essere seguita per arrivare al campo *sport* collegato

== Altre espressioni condizionali

[source]
.Like Expression
----
SELECT p FROM Player p
  WHERE p.name LIKE 'Mich%'
----

[source]
.Null Expression
----
SELECT t FROM Team t
  WHERE t.league IS NULL
----

[source]
.IS Empty Expression
----
SELECT p FROM Player p
  WHERE p.teams IS EMPTY
----

== Altre espres. condizionali^(2)^

[source]
.BETWEEN Expression
----
SELECT DISTINCT p FROM Player p
  WHERE p.salary BETWEEN :lowerSalary AND :higherSalary
----

[source]
.Operatori di comparazione
----
SELECT DISTINCT p1
  FROM Player p1, Player p2
  WHERE p1.salary > p2.salary AND p2.name = :name
----

== Uguaglianza nelle condizioni

[source,java]
----
public List<Person> havingHouse(House house) {
  return entityManager.createQuery(
      "SELECT p FROM Person JOIN p.houses h"
      + " WHERE h = :house", Person.class)
  .setParameter("house", house)
  .getResultList();
}
----

h = h:house::
Compara gli oggetti di tipo House relazionati a Person con l'oggetto House passato per parametro

Semantica dell'uguaglianza per le Entity::
Due entity dello stesso _abstract schema type_ sono considerate uguali se e solo se le loro chiavi primarie hanno lo stesso valore

== ORDER BY

[source]
----
SELECT o
  FROM Customer c JOIN c.orders o JOIN c.address a
  WHERE a.state = 'CA'
  ORDER BY o.quantity, o.totalcost
----


== GROUP BY e HAVING

[source]
----
SELECT c.status, AVG(o.totalPrice)
  FROM CustomerOrder o JOIN o.customer c
  GROUP BY c.status HAVING c.status IN (1, 2, 3)
----

== ALTRE FUNZIONI JPQL

* Stringhe: CONCAT, LENGTH, SUBSTRING, TRIM, LOWER, UPPER
* Aritmetiche: ABS, MOD, SQRT, SIZE
* Date/Time: CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP
* Subquery: simili alle subquery SQL
* Case Expression: CASE TYPE(p) WHEN...
* ....

Full Query Language Syntax::
https://docs.oracle.com/javaee/7/tutorial/persistence-querylanguage005.htm

== UPDATE e DELETE

Gli statemente *Update* e *delete* fornisco operazioni su un insieme di entity.

[source,bnf]
----
update_statement :: = update_clause [where_clause] 
delete_statement :: = delete_clause [where_clause]
----

* operano in accordo alle condizioni impostate nella WHERE
* la clausola WHERE segue le stesse regole valide per la SELECT

== Esempio Bulk Update

[source,java]
----
UPDATE Player p
  SET p.status = 'inactive'
  WHERE p.lastPlayed < :inactiveThresholdDate
----

Descrizione::
Imposta a _inactive_ tutti i giocatori che non giocano da molto tempo

== Esempio Bulk Delete

[source,java]
----
DELETE FROM Player p
  WHERE p.status = 'inactive'
  AND p.teams IS EMPTY
----

Descrizione::
Cancella tutti i giocatori inattivi che non appartengono a nessun Team


== Criteria API

* sono una alternativa in JPA 2.x per a JPQL
* le query sono dinamiche
* si compongono a partire da oggetti Java standard
** le query sono create in modo typesafe
* il `CriteriaBuidler` si ottiene utilizzando il metodo
`EntityManager::getCriteriaBuilder`

== Esempio query con Criteria API

[source,java]
.String-based Query
----
CriteriaBuilder builder = entityManager.getCriteriaBuilder();
CriteriaQuery<BlogEntry> criteriaQuery = builder.createQuery(BlogEntry.class);
Root<BlogEntry> be = criteriaQuery.from(BlogEntry.class);
ParameterExpression<String> title = builder.parameter(String.Class);
criteriaQuery.select(be).where(builder.equals(be.get("title"), title);

TypedQuery<BlogEntry> typedQuery = entityManager.createQuery(criteriaQuery);
typedQuery.setParameter(parameter, "il mio titolo");
typedQuery.getSingleResult(); // recupera il blogentry con "il mio titolo"
----

== Criteria API ≈ JPQL

* Criteria API e JPQL sono strettamente legate e con operatori analoghi nelle loro query. 
* gli sviluppatori familiari con la sintassi JPQL troverranno l'equivalente operazioni object-level nella Criteria API.

[source,java]
----
CriteriaBuilder cb = entityManager.getCriteriaBuilder();
CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
Root<Pet> pet = cq.from(Pet.class);
cq.select(pet);
TypedQuery<Pet> q = em.createQuery(cq);
List<Pet> allPets = q.getResultList();
----

è equivalente a 

[source,java]
----
List<Pet> allPets = 
  entityManager.createQuery("SELECT p FROM Pet p", Pet.class).getResultList();
----

== Metamodel API

* JPA2 prevede l'utilizzo di un Metamodel per ogni entity per garantire il typesafe delle query.
* un Metamodel è una classe i cui attributi corrispondono ai campi persistenti ed alle relazioni dell'entity.
* di solito la classe del Metamodel ha lo stesso il nome con un underscore (_) finale

== Esempio Metamodel

[source,java]
----
@Entity
public class Pet {
    @Id
    protected Long id;
    protected String name;
    protected String color;
    @ManyToOne
    protected Set<Person> owners;
    ...
}
----

[source,java]
----
@Static Metamodel(Pet.class)
public class Pet_ {
    public static volatile SingularAttribute<Pet, Long> id;
    public static volatile SingularAttribute<Pet, String> name;
    public static volatile SingularAttribute<Pet, String> color;
    public static volatile SetAttribute<Pet, Person> owners;
}
----

== Esempi utilizzo Metamodel

[source,java]
----
CriteriaBuilder cb = entityManager.getCriteriaBuilder();
CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
Root<Pet> pet = cq.from(Pet.class);
cq.where(cb.equal(pet.get(Pet_.name), "Fido"));
----

[source,java]
----
CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
Root<Pet> pet = cq.from(Pet.class);
cq.where(pet.get(Pet_.color).isNull());
----

[source,java]
----
CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
Root<Pet> pet = cq.from(Pet.class);
cq.where(pet.get(Pet_.color).in("brown", "black"));
----

== Generare il Metamodel

[source,xml]
----
<plugin>
    <groupId>org.bsc.maven</groupId>
    <artifactId>maven-processor-plugin</artifactId>
    <executions>
        <execution>
            <id>process</id>
            <goals>
                <goal>process</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
                <!-- source output directory -->
                <outputDirectory>target/metamodel</outputDirectory>
            </configuration>
        </execution>
    </executions>
    <dependencies>
      <dependency>        
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-jpamodelgen</artifactId>
        <version>4.3.11.Final</version>
      </dependency>
    </dependencies>
</plugin>
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>build-helper-maven-plugin</artifactId>
    <version>1.3</version>
    <executions>
        <execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>add-source</goal>
            </goals>
            <configuration>
                <sources>
                    <source>target/metamodel</source>
                </sources>
            </configuration>
        </execution>
    </executions>
</plugin>
----

== Criteria & Join

[source,java]
----
public List<Pet> byOwnerName(String ownerName) {
  CriteriaBuilder cb = entityManager.getCriteriaBuilder();
  CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);

  Root<Pet> pet = cq.from(Pet.class);
  Join<Pet, Owner> owner = pet.join(Pet_.owners); 
  cq.select(pet).where(cb.equal(owner.get(Owner_.name), ownerName));

  return entityManager.createQuery(criteriaQuery.where()).getResultList();
}
----

== Comporre i predicati

 * I predicati sono componibili con: and, or, not

[source,java]
----
CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
Root<Pet> pet = cq.from(Pet.class);
cq.where(cb.equal(pet.get(Pet_.name), "Fido")
    .and(cb.equal(pet.get(Pet_.color), "brown")));
----

== Ordinare i risultati

[source,java]
----
CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
Root<Pet> pet = cq.from(Pet.class);
cq.select(pet);
cq.orderBy(cb.desc(pet.get(Pet_.birthday)));
----

[source,java]
----
CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
Root<Pet> pet = cq.from(Pet.class);
Join<Owner, Address> address = pet.join(Pet_.owners).join(Owner_.address);
cq.select(pet);
cq.orderBy(cb.asc(address.get(Address_.postalCode)));
----

[source,java]
----
CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
Root<Pet> pet = cq.from(Pet.class);
Join<Pet, Owner> owner = pet.join(Pet_.owners);
cq.select(pet);
cq.orderBy(cb.asc(owner.get(Owner_.lastName)), owner.get(Owner_.firstName)));
----


== GroupBy & Having

[source,java]
----
CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
Root<Pet> pet = cq.from(Pet.class);
cq.groupBy(pet.get(Pet_.color));
cq.having(cb.in(pet.get(Pet_.color)).value("brown").value("blonde"));
----

Descrizione::
Restituisce la lista di Pet il cui Owner si chiama come il parametro _ownerName_ passato


== JPQL vs Criteria Query

* Vantaggi JPQL
** le query JPQL sono poche righe, coincise e più leggibili
** gli sviluppatori già familiari con SQL le imparano velocemente
** le JPQL NamedQuery possono essere definite e riutilizzate facilmente

== JPQL vs Criteria Query^(2)^
* Svantaggi JPQL
** JPQL query non sono typesafe
** richiedono un cast quando si leggono i risultati dall'entityManager
** sono sottoposte a problemi di type-casting non intercettabili a compile time
** in caso di refactoring delle Entity non c'è nessun controllo sulle stringhe JPQL utilizzate

== JPQL vs Criteria Query^(3)^

* Vantaggi Criteria Query
** permettono di definire le query a livello applicativo con oggetti riutlizzabili
** hanno migliori performance perché non necessitano il parsing della query (String) ogni volta
** sono typesafe e non richiedono type casting
** sono un API Java e non richiedono di imparare un nuovo linguaggio
** in caso di rifattorizzazione le query sono parzialmente rifattorizzate automaticamente

== JPQL vs Criteria Query^(4)^
* Svantaggi di Criteria Query
** sono più prolisse delle query JPQL
** richiedono la creazione di molti oggetti ed eseguire diversi metodi per sottomettere le query

== Implementazioni JPA

Esistono varie implementazioni JPA che tipicamente sono utilizzati all'interno
di application server:

* Hibernate, in JBoss/RedHat
* EclipseLink, Oracle
* OpenJPA
...

== Utilizzare JPQL in Spring

* org.springframework.data.jpa.repository.Query

[source,java]
----
public interface ArticleDao extends PagingAndSortingRepository<Article, Integer> {
  @Query("SELECT a FROM Article a WHERE a.author.surname = ?1")
  List<Article> findByAuthorSurname(String surname);
}
----

== Evoluzione del database

* hibernate.ddl-auto =update VS database evolution
* https://flywaydb.org/getstarted/how


== Riferimenti ed approfondimenti

* Java Platform, Enterprise Edition: The Java EE Tutorial -> Persistence
** https://docs.oracle.com/javaee/7/tutorial/partpersist.htm#BNBPY


