= Introduzione a JPA^(3)^
Cristian Lucchesi <cristian.lucchesi@gmail.com>
2016-02-23
:source-highlighter: highlightjs
:backend: revealjs
:revealjs_theme: night
:revealjs_slideNumber: true
:sourcedir: ../main/java

== Relazioni e loro caratteristiche

* gli oggetti possono contenere uno o più riferimenti ad altri oggetti
** questi riferimenti prendono il nome di *relazioni*
* le relazioni hanno diverse caratteristiche
** la prima è la *direzionalità*, una relazione potrà essere:
*** unidirezionale se un oggetto fa riferimento ad un altro ma non avviene il contrario
*** bidirezionale se il riferimento tra gli oggetti è reciproco

== Relazioni bidirezionali
[source,java]
----
@Entity
public class Person {
  private Account account;
}
@Entity
public class Account {
  // Possessore
  private Person owner;
}
----

La Person ha una relazione con Account e viceversa.

== Relazioni unidirezionali

[source,java]
----
@Entity
public class Person {
  //... Altre proprietà
  private Province bornIn;
}
@Entity
public class Province {
  private String name;
}
----

Person ha una relazione con Province ma non viceversa.

== Relazioni e opzionalità

** altra caratteristica delle relazioni è l'opzionalità:
*** non è detto che la relazione debba esistere necessariamente.
*** Se non è obbligatoria, la relazione si dice opzionale.

== Relazioni e molteplicità^(3)^

* molteplicità della relazione
* la relazione può sussistere verso uno o più oggetti, in entrambe le direzioni
* si identificano pertanto tre tipi di relazioni
** uno a uno 
** uno a molti
** molti a molti

JPA permette di gestire le relazioni e di risparmiarci di scrivere molto codice

== Relazione uno a uno unidirezionale

* si utilizza l’annotazione *@OneToOne*

[source,java]
----
@Entity @Table(name="persons")
public class Person {
  @OneToOne
  private Account account;
}
@Entity @Table(name="accounts")
public class Account {
  // Non c'è il campo Person
}
----

* nelle relazioni unidirezionali l'annotazione è solo nell’entità che possiede il riferimento (_owning side_)
* la tabella _persons_ avrà una colonna con la chiave esterna che si riferisce alla tabella _accounts_.

== Relazione uno a uno bidirezionale

[source,java]
----
@Entity @Table(name="persons")
public class Person {
  @OneToOne
  private Account account;
}
@Entity @Table(name="accounts")
public class Account {
  @OneToOne(mappedBy="account")
  private Person person;
}
----

* l'annotazione @OneToOne è su entrambe le entità (_owning side_ e _inverse side_)
* l'attributo *mappedBy* specifica il *nome* della proprietà java utilizzata nella @OneToOne che è _owning side_

== L'importanza dell'owning side

* il Persistence Runtime JPA (es. Hibernate) effettua aggiornamenti della relazione sul db solo quando si cambia l'owning side
[source,java]
----
@Entity @Table(name="persons")
public class Person {
  @OneToOne
  private Account account;
}
@Entity @Table(name="accounts")
public class Account {
  @OneToOne(mappedBy="account")
  private Person person;
}
...
Person p = entityManager.getReference(Person.class, 1L);
account.person = person; // Non viene modfificato il db

Account a = entityManager.getReference(Account.class, 1L);
person.account = a; // viene aggiornato il db
----


== Annotazione @JoinColumn

* @JoinColumn permette di personalizzare la relazione:
** *name*: (String default il nome della variabile)
*** cambia il nome della colonna sul db
** *insertable*: (boolean default true) 
*** se false la colonna viene omessa nella insert
** *updatable*: (boolean default true) 
*** se false la colonna viene omessa nella update

== Annotazione @JoinColumn^(2)^

* @JoinColumn permette di personalizzare la relazione:
** *nullable* (boolean default true)
*** utilizzata per determinare il tipo di JOIN eseguita da jpa (INNER vs LEFT)
** columnDefinition (String default "")
*** frammento di SQL da utilizzare per la DDL della colonna

== Annotazione @JoinColumn^(3)^

[source,java]
----
@Entity @Table(name="persons")
public class Person {
  @OneToOne
  @JoinColumn(name="account_id", updatable = false)
  private Account account;
}
----

== @NamedQuery

* Si possono definire query statiche con nome
** Raccomandate perché le query usufruiscono del sistema di *cache*
[source,java]
----
@NamedQuery(name="ordered",  query="SELECT e FROM BlogEntry e ORDER BY e.date ASC")
public class BlogEntry {
...
----

[source,java]
----
public List<BlogEntry> allEntriesOrdered() {
    return entityManager.createNamedQuery("ordered", BlogEntry.class).getResultList();
}
----

== Criteria API

* sono una alternativa in JPA 2.x per a JPQL
* le query sono dinamiche
* si compongono a partire da oggetti Java standard
** le query sono create in modo typesafe
* il `CriteriaBuidler` si ottiene utilizzando il metodo
`EntityManager::getCriteriaBuilder`

== Esempio di query con Criteria API

[source,java]
----
CriteriaBuilder builder = entityManager.getCriteriaBuilder();
CriteriaQuery<BlogEntry> criteriaQuery = builder.createQuery(BlogEntry.class);
Root<BlogEntry> be = criteriaQuery.from(BlogEntry.class);
ParameterExpression<String> title = builder.parameter(String.Class);
criteriaQuery.select(be).where(builder.equals(be.get("title"), title);

TypedQuery<BlogEntry> typedQuery = entityManager.createQuery(criteriaQuery);
typedQuery.setParameter(parameter, "il mio titolo");
typedQuery.getSingleResult(); // recupera il blogentry con "il mio titolo"
----

== Implementazioni JPA

Esistono varie implementazioni JPA che tipicamente sono utilizzati all'interno
di application server:

* Hibernate, in JBoss/RedHat
* EclipseLink, Oracle
* OpenJPA
...
