= Introduzione a JPA
Marco Andreini <marco.andreini@besmartbeopen.it>
2016-02-18
:source-highlighter: highlightjs
:backend: revealjs
:revealjs_theme: night
:revealjs_slideNumber: true
:sourcedir: ../main/java

== Architettura multi strato

Per creare applicazioni - anche complesse - si può utilizzare una architettura
multi-strato (_n-tier_).

Ciascuno strato:

 - si occupa di un insieme di funzionalità logicamente separato;
 - comunica con il precedente e il successivo;
 - è sviluppato separatamente e indipendentemente dagli altri.


== Architettura a tre livelli
Le applicazioni web sono spesso strutturate su *three-tier architecture*:

1. livello di presentazione, con la quale si interagisce direttamente con l'utente
2. livello applicativo (_businness logic_), si occupa della logica di funzionamento
3. livello dati, si occupa dell'immagazzinamento dei dati su database

== Object Relational Mapping
* L'ORM si occupa di automatizzare il processo di trasformazione dei dati tra
gli oggetti (istanze di classi) e i database.
* Perché è utile?

** semplifica enormemente il lavoro di interfacciamento al database;
** evita di dover scrivere le procedure di trasformazione a mano;
** ci vogliamo concentrare sulla _logica di funzionamento_ e non sulla
 struttura relazionale del database.

== ORM: altri benefici

- Permette una eventuale sincronizzazione automatica degli oggetti su database
- È piuttosto indipendente dal tipo di database
- Astrazione sui metodi di interrogazione
- Prestazioni: utilizzando meccanismi di cache semi-automatici

== Java Persistence API

JPA è una specifica java (_JSR_) per *accedere*, *memorizzare* e *gestire* dati di
oggetti Java specifici e database relazionali.

È confinato nel package `javax.persistence` e non fa parte della dotazione
standard JavaSE.

È considerato l'_ORM_ standard in ambiente Java.

  È stato inizialmente definito nella specifica EJB3.0.

== Hibernate come JPA
Hibernate è un ORM che implementa la specifica JPA.

- Esistono diverse specifiche JPA (1.0, 2.0, 2.1…)
- Queste specifiche sono implementate in Hibernate in varie versioni.
- Noi utilizzeremo come riferimento la specifica JPA 2.0, che è implementata
  in Hibernate a partire dalla 4.0.

== Una entity
[source,java]
----
@Entity // genererà una TABLE di nome blog_entry
public class BlogEntry {

  @Id @GeneratedValue // genera una INT PRIMARY KEY autoincrementale di nome id
  private Integer id;

  @Column(nullable=false) // genererà un campo title di tipo VARCHAR NOT NULL
  private String title;

  private String summary; // semplici VARCHAR

  private String body;

  @Temporal(TemporalType.TIMESTAMP) // genererà un campo date di tipo 'TIMESTAMP'
  private Date date;
}
----

== JPA e POJO
Si utilizzano oggetti di tipo POJO (Plain Old Java Object) e
la persistenza riguarda:

- il salvataggio dei valori dei campi di questi oggetti
- la loro consultazione
- la loro gestione (aggiornamento, cancellazione,...)
- ogni oggetto tipicamente rappresenta una riga di una tabella

== Annotazioni JPA

Le caratteristiche degli oggetti coinvolti - prevalentemente entity - sono
definite da annotazioni specifiche.

Queste annotazioni indicano quale comportamento deve avere il JPA (ciò che
implementa la specifica JPA, per esempio Hibernate).

 In precedenza si utilizzavano metadati inseriti appositi file XML, separati
 dal codice Java.

  Si trovano ancora `XML` di Hibernate su software un po' datati.

== @Entity
Le entity in JPA sono gli oggetti persistenti.

Per esempio i dati degli articoli di un blog possono essere riassunti una
apposita entity, annotata appositamente con `@Entity`:
[source,java]
----
include::{sourcedir}/it/besmartbeopen/model/BlogEntry.java[lines=12..28]
----

== @Id
Occorre annotare con `@Id` il campo che identifica la chiave primaria:

- Solitamente è di tipo numerico o stringa
- Ci deve essere un solo campo annotato con `@Id` per entity.
- Visto che le entity sono confrontate tramite il metodo equals, occorre che
  si utilizzi in questi confronti il campo annotato con `@Id`.

== Chiavi primarie

- Se necessario è possibile creare chiavi primarie composte – anche se
  solitamente non è consigliabile.

- Si può indicare una strategia per la generazione automatica dei valori delle
chiavi primarie con:
[source,java]
----
include::{sourcedir}/it/besmartbeopen/model/BlogEntry.java[lines=15..18]
----

== @Column

L'annotazione `@Column` può essere utilizzata su tutti i campi dell'oggetto per:

* indicare il nome della colonna corrispondente (con `name=...`), che
altrimenti sarà il nome del campo (opportunamente traslato)
* indicare se il campo può assumere i valori `null` (_default_) o meno (con `nullable=false`)
* indicare se la colonna corrispondente deve avere una chiave univoca (con `unique=true`)
* Usati da usare in casi specifici, più di rado: columnDefinition, length, insertable, updatable, ...

== @Table
Con @Table si possono annotare le entity con informazioni aggiuntive, permettendo di indicare:

* il nome della tabella (altrimenti è quello dell'entity)
* il nome del catalogo
* il nome dello schema
* eventuali vincoli di univocità (uniqueConstraints)
* eventuali indici (indexes)

== Persistence Unit

* è definito dall'insieme di classi gestite da un'istanza dell'EntityManager
* mappa un insieme di classi di entity su un database relazionale
* effettua la serializzazione e deserializzazione controllate verso/dal database relazionale

== Persistence Context
* è l'insieme delle istanze di entity in un certo insieme di dati
* conosce lo stato (`detached`, `managed`,...) delle istanze di entity correlate

== EntityManager

[%step]
* permette di interagire col _Persistence Context_
* ha una API per gestire le istanze delle entity, interagendo col loro stato
* permette di caricare, salvare, cercare... le istanze delle entity
* In modo dipendente dal framework in uso l'entityManager è:
** Injected dal framework in automatico (es. @PersistenceContext)
** Creato a partire dall'`EntityManagerFactory`, creato e configurato una sola
volta all'avvio dell'applicazione.


== Operazioni sulle entity
[%step]
* creazione -> `EntityManager::persist`
* recupero con chiave primaria
** `EntityManager::find`
** `EntityManager::getReference`
* cancellazione -> `EntityManager::remove`
* salvataggi automatici -> con la gestioni delle transazioni
* ricerche -> `JPQL`

== EntityManager::persist

gli oggetti annotati come entità sono regolari oggetti java fino a quando non
vengono resi persistenti dall'`EntityManager`
[source,java]
----
 entityManager.persist(myBlogEntry);
----
* il metodo persist(entityObject) rende persistente l'entità nel database
(esegue la `INSERT` SQL)

== persist^(2)^

* nella chiamata alla `persist` viene verificato che non ci siano oggetti
con lo stesso *id* nel database, e nel caso viene sollevata una runtime
exception: `EntityExistsException`

* se l'oggetto non è trovato questo metodo restituisce un'eccezione `EntityNotFFoundException`
* l'istanza è prelevata in modo lazely (non si prelavano i valori delle proprietà dal database)
* lo stato dell'entità (title, excerpt, body...) sono prelevati la prima volta che si accede all'oggetto

== Esempio di persist
[source,java]
----
  BlogEntry myBlogEntry = new BlogEntry();
  myBlogEntry.setDate(new Date());
  myBlogEntry.setTitle("titolo dell'articolo");
  myBlogEntry.setExcerpt("intestazione dell'articolo");
  myBlogEntry.setBody("corpo dell'articolo");

  entityManager.persist(myBlogEntry);
----

[options="header"]
|===
|id |title |excerpt |body |date

|1
|titolo dell'articolo
|intestazione dell'articolo
|corpo dell'articolo
|2016-02-01 16:00:00

...
|===


== EntityManager::find

il metodo find è utilizzabile per interrogare gli entity object
[source,java]
----
 BlogEntry entry = entityManager.find(BlogEntry.class, myBlogId);
----
* il metodo find() accetta due paremetri
** l'oggetto Entity
** il valore della chiave primaria
* se non ci sono risultati per la ricerca con la chiave indicata, l'operazione restituisce null.
* se invece ci sono l'oggetto restituito dall'`EntityManager` diventa direttamente utilizzabile in Java

== EntityManager::getReference

accetta gli stessi parametri del metodo find
[source,java]
----
 BlogEntry entry = entityManager.getReference(BlogEntry.class, myBlogId);
----

== EntityManager::remove

si usa per cancellare una istanza della entità (quindi una riga) dal database:
[source,java]
----
 entityManager.remove(myBlogEntry);
----
* l'entityObject passato deve essere gestito dall'entityManager pena il fallimento della rimozione
* l'operazione di cancellazione dal db può avvenire successivamente (dopo la `EntityManager::flush()`)
* dopo la chiamata, l'entity diventerà "detached" dal entityManager e non più gestita
** cioè sono interrotti gli automatismi di aggiornamento e di caricamento dei dati verso il db.


== Transazioni


== Ricerche `JPQL`

E se volessimo cercare una `Person` per nome o cognome?

[source,java]
----
include::{sourcedir}/it/besmartbeopen/query/Queries.java[lines=15..20]
----

== @MappedSuperclass

Viene utilizzata per creare una gerarchia di oggetti che hanno dei campi in
comune:

[source,java]
----
include::{sourcedir}/it/besmartbeopen/model/BaseEntity.java[lines=11..21;46]
----

== @MappedSuperclass^(2)^

Così altri oggetti possono ereditarne i campi, mantenendo le informazioni su
tabelle diverse:

[source,java]
----
include::{sourcedir}/it/besmartbeopen/model/Person.java[lines=6..19]
----

== Gerarchia di entity

Notare che gli oggetti Person e quindi le righe della tabella person hanno:

* firstname, lastname, phone, email
* ma anche id, createdAt, updatedAt



