= Introduzione a JPA
Marco Andreini <marco.andreini@gmail.com>
2016-02-18
:source-highlighter: highlightjs
:backend: revealjs
:revealjs_theme: night
:revealjs_slideNumber: true

== Architettura multi strato

Per creare applicazioni - anche complesse - si può utilizzare una architettura
multi-strato (_n-tier_).

Ciascuno strato:

 - si occupa di un insieme di funzionalità logicamente separato;
 - comunica con il precedente e il successivo;
 - è sviluppato separatamente e indipendentemente dagli altri.


== Architettura a tre livelli
Le applicazioni web sono spesso strutturate su *three-tier architecture*:

1. livello di presentazione, con la quale si interagisce direttamente con l'utente
2. livello applicativo (_businness logic_), si occupa della logica di funzionamento
3. livello dati, si occupa dell'immagazzinamento dei dati su database

== Object Relational Mapping
* L'ORM si occupa di automatizzare il processo di trasformazione dei dati tra
gli oggetti (istanze di classi) e i database.
* Perché è utile?

** semplifica enormemente il lavoro di interfacciamento al database;
** evita di dover scrivere le procedure di trasformazione a mano;
** ci vogliamo concentrare sulla _logica di funzionamento_ e non sulla
 struttura relazionale del database.

== ORM: altri benefici

- Permette una eventuale sincronizzazione automatica degli oggetti su database
- È piuttosto indipendente dal tipo di database
- Astrazione sui metodi di interrogazione
- Prestazioni: utilizzando meccanismi di cache semi-automatici

== Java Persistence API

JPA è una specifica java (_JSR_) per *accedere*, *memorizzare* e *gestire* dati di
oggetti Java specifici e database relazionali.

È considerato l'_ORM_ standard in ambiente Java.

  È stato inizialmente definito nella specifica EJB3.0.

== Hibernate come JPA
Hibernate è un ORM che implementa la specifica JPA.

- Esistono diverse specifiche JPA (1.0, 2.0, 2.1…)
- Queste specifiche sono implementate in Hibernate in varie versioni.
- Noi utilizzeremo come riferimento la specifica JPA 2.0, che è implementata
  in Hibernate a partire dalla 4.0.

== Una entity
[source,java]
----
@Entity // genererà una TABLE di nome blog_entry
public class BlogEntry {

  @Id @GeneratedValue // genera una INT PRIMARY KEY autoincrementale di nome id
  private Integer id;

  @Column(nullable=false) // genererà un campo title di tipo VARCHAR NOT NULL
  private String title;

  private String summary; // semplici VARCHAR

  private String body;

  @Temporal(TemporalType.TIMESTAMP) // genererà un campo date di tipo 'TIMESTAMP'
  private Date date;
}
----

== JPA e POJO
Si utilizzano oggetti di tipo POJO (Plain Old Java Object) e
la persistenza riguarda:

- il salvataggio dei valori dei campi di questi oggetti
- la loro consultazione
- la loro gestione (aggiornamento, cancellazione,...)

== Annotazioni JPA

Le caratteristiche degli oggetti coinvolti - prevalentemente entity - sono
definite da annotazioni specifiche.

Queste annotazioni indicano quale comportamento deve avere il JPA (ciò che
implementa la specifica JPA, per esempio Hibernate).

 In precedenza si utilizzavano metadati inseriti appositi file XML, separati
 dal codice Java.

  Si trovano ancora `XML` di Hibernate su software un po' datati.

== @Entity
Le entity in JPA sono gli oggetti persistenti.

Per esempio i dati degli articoli di un blog possono essere riassunti una
apposita entity, annotata appositamente con `@Entity`:
[source,java]
----
include::../main/java/it/besmartbeopen/model/BlogEntry.java[lines=12..28]
----

== @Id
Occorre annotare con `@Id` il campo che identifica la chiave primaria:

- Solitamente è di tipo numerico o stringa
- Ci deve essere un solo campo annotato con `@Id` per entity.
- Visto che le entity sono confrontate tramite il metodo equals, occorre che
  si utilizzi in questi confronti il campo annotato con `@Id`.

== Chiavi primarie

- Se necessario è possibile creare chiavi primarie composte – anche se
  solitamente non è consigliabile.

- Si può indicare una strategia per la generazione automatica dei valori delle
chiavi primarie con:
[source,java]
----
include::../main/java/it/besmartbeopen/model/BlogEntry.java[lines=15..18]
----

